### PR TITLE
Refactored code w/o any addition

### PR DESCRIPTION
**Pull request by victorgveloso**
### Description
- make_request generalized to any API method call
- Search class methods' docstrings misstyping fixed and pproject search_api action modified to project
- removed some of search_api cloned code, created version kwarg to project_dependencies action defaulted to "latest"
- more strict typing added to Subscribe class code
- decreased a lot of redundant code from sub_api favoring idiomatic solution

Obs: Due to no public API modification, i didn't create additional automatic tests.

### Checklist
- [X] Code works
- [x] Created tests 
- [X] All tests pass
- [X] Passes Flake8
- [X] Follows Black style (with 88 character line length)
- [ ] Doc strings added if applicable
- [ ] Docs extended, if applicable
- [X] Doc strings modified

### CODE REVIEW

**Comment by victorgveloso** [comment]
New modifications were pushed to this PR including new test cases (#57) , more refactoring, kwargs['version'] included (#45) , fixed some naming divergences between libraries.io API and pybraries (manager->platform and package->project)

**Comment by discdiver** [comment]
Thanks, Victor! I'll plan to take a look at this over the weekend.

**Comment by victorgveloso** [comment]
This version has 96% code coverage!

**Comment by discdiver** [comment]
Great work with this @victorgveloso! I had to change an import to `from pybraries.pagination import fix_pages` https://github.com/pybraries/pybraries/commit/0f0576b73a18ac731f727d7eada69ada9204ed4a#diff-521da22afd4cfddccf8ca0b5a77d3aca to get it to run.

And I updated the docs and a little code formatting. Thanks so much for your work! 👍 Hope you find the package useful!

**Pull request merged**
